#!/usr/bin/env python3
"""Write synthetic spans straight into Iceberg through Trino.

    python scripts/seed_iceberg.py seed --events 600 --seed 7
    python scripts/seed_iceberg.py inject-bad-row
    python scripts/seed_iceberg.py revert-bad-row

Two jobs, and they are related.

**CI.** The `quality` job in .github/workflows/ci.yml runs the real dbt build and
the real Great Expectations checkpoint, which need rows in
``lake.raw.trace_events``. Producing them the normal way means Kafka, Schema
Registry, six Flink jars and a 30s checkpoint wait -- a slow, flaky job that
mostly tests the cold path, which ADR-004 already verified. This writes the same
13-column rows directly, so CI exercises the part it is actually gating: the
models, the tests and the expectations.

**Fault injection.** ``inject-bad-row`` puts one span with ``cost_usd = -1`` into
the table so the quality gate can be watched to FAIL and then, after
``revert-bad-row``, to pass again. A gate nobody has seen fail is a gate nobody
should trust.

On "only Flink writes to Iceberg"
---------------------------------
ADR-004 #2's rule is about the warehouse where Flink is the writer, and it still
holds there. In CI there is no Flink and no Kafka -- the warehouse is created
empty by ``stream.flink.create_tables`` and destroyed with the runner -- so
there is no writer to conflict with. Locally, ``seed`` REFUSES a table that
already has rows unless ``--force``, so it cannot quietly mix synthetic rows
into data Flink produced. ``inject-bad-row`` is the deliberate exception: it
writes exactly one marked row and prints how to remove it. See ADR-006 #9.
"""

from __future__ import annotations

import argparse
import random
import sys
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from analytics.trino_client import TrinoClient  # noqa: E402

#: The table every subcommand writes to unless --table says otherwise. The flag
#: exists so the seeder itself can be rehearsed against a scratch table without
#: touching a warehouse that holds real Flink-written rows -- which is exactly
#: what tests cannot do and what a reviewer will want to do once.
DEFAULT_RAW_TABLE = "lake.raw.trace_events"

#: The injected row's span_id, fixed so revert-bad-row can find it without
#: being told and so a leftover row is identifiable by grep rather than by
#: remembering. Not a uuid4: it must be recognisable on sight.
BAD_SPAN_ID = "00000000000000000000000000000bad"

MODELS = ("claude-haiku-4-5", "claude-sonnet-5")

# Same shapes scripts/gen_traffic.py emits, because the point of a fixture is to
# look like production. An ok turn is AGENT_STEP + RETRIEVAL + LLM_CALL; an
# error turn is AGENT_STEP + TOOL_CALL, both status='error', the TOOL_CALL
# carrying error_class=TimeoutError -- which is what makes fct_tool_reliability's
# timeout_rate non-zero against seeded data too.
SPANS_PER_OK_TURN = 3
SPANS_PER_ERR_TURN = 2


def _sql_str(value: str) -> str:
    """Single-quote a string literal for SQL, escaping embedded quotes.

    Every value here is generated by this script -- uuid hex, a model name from
    MODELS, a fixed label -- so nothing caller-controlled reaches it. The
    escaping is belt and braces for the day someone adds a --tool-name flag.
    """
    return "'" + value.replace("'", "''") + "'"


def _map_literal(attributes: dict[str, str]) -> str:
    if not attributes:
        return "MAP(ARRAY[], ARRAY[])"
    keys = ", ".join(_sql_str(k) for k in attributes)
    values = ", ".join(_sql_str(v) for v in attributes.values())
    return f"MAP(ARRAY[{keys}], ARRAY[{values}])"


def _row(
    *,
    trace_id: str,
    span_id: str,
    parent_span_id: str | None,
    session_id: str,
    event_type: str,
    model: str | None,
    prompt_tokens: int | None,
    completion_tokens: int | None,
    latency_ms: float,
    cost_usd: float | None,
    status: str,
    ts: datetime,
    attributes: dict[str, str],
) -> str:
    """One VALUES tuple, in the column order of contracts/trace_event_v1.avsc."""
    return (
        "("
        f"{_sql_str(trace_id)}, {_sql_str(span_id)}, "
        f"{_sql_str(parent_span_id) if parent_span_id else 'CAST(NULL AS VARCHAR)'}, "
        f"{_sql_str(session_id)}, {_sql_str(event_type)}, "
        f"{_sql_str(model) if model else 'CAST(NULL AS VARCHAR)'}, "
        f"{prompt_tokens if prompt_tokens is not None else 'CAST(NULL AS BIGINT)'}, "
        f"{completion_tokens if completion_tokens is not None else 'CAST(NULL AS BIGINT)'}, "
        f"{latency_ms:.3f}, "
        f"{cost_usd if cost_usd is not None else 'CAST(NULL AS DOUBLE)'}, "
        f"{_sql_str(status)}, "
        f"TIMESTAMP '{ts.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}', "
        f"{_map_literal(attributes)}"
        ")"
    )


def build_rows(events: int, sessions: int, error_rate: float, base: datetime) -> list[str]:
    """Deterministic given a seeded RNG -- CI compares nothing across runs, but a
    fixture that changes shape between runs makes a failure impossible to
    reproduce."""
    rows: list[str] = []
    turns_total = max(1, events // SPANS_PER_OK_TURN)
    turns_per_session = max(1, turns_total // max(1, sessions))
    offset = 0

    while len(rows) < events:
        session_id = uuid.UUID(int=random.getrandbits(128)).hex
        for _ in range(turns_per_session):
            if len(rows) >= events:
                break
            trace_id = uuid.UUID(int=random.getrandbits(128)).hex
            step_span = uuid.UUID(int=random.getrandbits(128)).hex
            ts = base + timedelta(milliseconds=offset * 137)
            offset += 1
            errored = random.random() < error_rate

            rows.append(_row(
                trace_id=trace_id, span_id=step_span, parent_span_id=None,
                session_id=session_id, event_type="AGENT_STEP", model=None,
                prompt_tokens=None, completion_tokens=None,
                latency_ms=random.uniform(20.0, 300.0), cost_usd=None,
                status="error" if errored else "ok", ts=ts,
                attributes={"name": "agent_turn"},
            ))

            if errored:
                rows.append(_row(
                    trace_id=trace_id, span_id=uuid.UUID(int=random.getrandbits(128)).hex,
                    parent_span_id=step_span, session_id=session_id,
                    event_type="TOOL_CALL", model=None,
                    prompt_tokens=None, completion_tokens=None,
                    latency_ms=random.uniform(1.0, 8.0), cost_usd=None,
                    status="error", ts=ts,
                    attributes={
                        "name": "lookup_order",
                        "tool": "orders_api",
                        "error_class": "TimeoutError",
                        "error_message": "orders_api did not respond in 2s",
                    },
                ))
                continue

            rows.append(_row(
                trace_id=trace_id, span_id=uuid.UUID(int=random.getrandbits(128)).hex,
                parent_span_id=step_span, session_id=session_id,
                event_type="RETRIEVAL", model=None,
                prompt_tokens=None, completion_tokens=None,
                latency_ms=random.uniform(1.0, 8.0), cost_usd=None,
                status="ok", ts=ts,
                attributes={"name": "vector_search", "index": "docs-v1", "top_k": "4"},
            ))

            prompt_tokens = random.randint(180, 420)
            completion_tokens = random.randint(40, 160)
            rows.append(_row(
                trace_id=trace_id, span_id=uuid.UUID(int=random.getrandbits(128)).hex,
                parent_span_id=step_span, session_id=session_id,
                event_type="LLM_CALL", model=random.choice(MODELS),
                prompt_tokens=prompt_tokens, completion_tokens=completion_tokens,
                latency_ms=random.uniform(2.0, 30.0),
                cost_usd=round(prompt_tokens * 1e-6 + completion_tokens * 5e-6, 6),
                status="ok", ts=ts,
                attributes={"name": "chat_completion", "finish_reason": "stop"},
            ))

    return rows[:events]


def _insert(client: TrinoClient, table: str, rows: list[str], batch: int = 200) -> int:
    """INSERT in batches. One 600-row VALUES list is a single very large SQL
    string and a single Iceberg commit; batching keeps both bounded and, on the
    SQLite-backed catalog, keeps each commit short (see ADR-006 #8)."""
    written = 0
    for start in range(0, len(rows), batch):
        chunk = rows[start:start + batch]
        client.execute(f"INSERT INTO {table} VALUES\n" + ",\n".join(chunk))
        written += len(chunk)
        print(f"  inserted {written}/{len(rows)}")
    return written


def cmd_seed(client: TrinoClient, args: argparse.Namespace) -> int:
    table = args.table
    existing = client.execute(f"SELECT count(*) FROM {table}").scalar()
    if existing and not args.force:
        print(
            f"REFUSED: {table} already holds {existing} rows.\n\n"
            "This writes synthetic spans. Mixing them into rows Flink produced would\n"
            "make every later count ambiguous and there is no way to tell them apart\n"
            "afterwards. Re-run with --force if that is genuinely what you want, or\n"
            "reset the warehouse first:\n\n"
            "    python -m stream.flink.create_tables --recreate\n"
        )
        return 1

    random.seed(args.seed)
    base = datetime.now(UTC).replace(tzinfo=None) - timedelta(minutes=args.events // 4)
    rows = build_rows(args.events, args.sessions, args.error_rate, base)
    print(f"seeding {len(rows)} spans into {table} (seed={args.seed})")
    _insert(client, table, rows)

    total = client.execute(f"SELECT count(*) FROM {table}").scalar()
    print(f"\n{table} now holds {total} rows")
    return 0


def cmd_inject(client: TrinoClient, args: argparse.Namespace) -> int:
    """Put one impossible row into the raw table, to watch the gate catch it."""
    table = args.table
    already = client.execute(
        f"SELECT count(*) FROM {table} WHERE span_id = {_sql_str(BAD_SPAN_ID)}"
    ).scalar()
    if already:
        print(f"the bad row is already present ({already}); nothing to do")
        return 0

    ts = datetime.now(UTC).replace(tzinfo=None)
    row = _row(
        trace_id="00000000000000000000000000000bad",
        span_id=BAD_SPAN_ID,
        parent_span_id=None,
        session_id="00000000000000000000000000000bad",
        event_type="LLM_CALL",
        model="claude-haiku-4-5",
        prompt_tokens=100,
        completion_tokens=10,
        # The whole point. cost_usd >= 0 is asserted by a dbt accepted_range on
        # staging AND by a blocking Great Expectations bound on fct_sessions and
        # fct_model_costs, so this single row should fail both gates.
        latency_ms=1.0,
        cost_usd=-1.0,
        status="ok",
        ts=ts,
        attributes={"name": "chat_completion", "injected": "true"},
    )
    client.execute(f"INSERT INTO {table} VALUES\n{row}")
    print(
        f"injected one span with cost_usd = -1.0 (span_id {BAD_SPAN_ID})\n\n"
        "Now:  make dbt-build   -> expect the staging cost/latency range test to FAIL\n"
        "      make quality     -> expect the blocking cost bound to FAIL\n"
        "Then: python scripts/seed_iceberg.py revert-bad-row\n"
    )
    return 0


def cmd_revert(client: TrinoClient, args: argparse.Namespace) -> int:
    table = args.table
    before = client.execute(
        f"SELECT count(*) FROM {table} WHERE span_id = {_sql_str(BAD_SPAN_ID)}"
    ).scalar()
    if not before:
        print("no injected row present; nothing to do")
        return 0
    client.execute(f"DELETE FROM {table} WHERE span_id = {_sql_str(BAD_SPAN_ID)}")
    after = client.execute(
        f"SELECT count(*) FROM {table} WHERE span_id = {_sql_str(BAD_SPAN_ID)}"
    ).scalar()
    print(f"removed {before} injected row(s); {after} remain")
    print("Now:  make dbt-build && make quality   -> expect both green again")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--url", default=None, help="Trino base URL (default: $AGENTLAKE_TRINO)")
    parser.add_argument(
        "--table", default=DEFAULT_RAW_TABLE,
        help=f"fully-qualified target table (default: {DEFAULT_RAW_TABLE})",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    seed = sub.add_parser("seed", help="write synthetic spans into lake.raw.trace_events")
    seed.add_argument("--events", type=int, default=600)
    seed.add_argument("--sessions", type=int, default=20)
    seed.add_argument("--error-rate", type=float, default=0.08)
    seed.add_argument("--seed", type=int, default=7, help="RNG seed (default 7)")
    seed.add_argument(
        "--force", action="store_true",
        help="seed even though the table already has rows -- mixes synthetic data "
             "into real data irreversibly",
    )
    seed.set_defaults(func=cmd_seed)

    inject = sub.add_parser("inject-bad-row", help="insert one span with cost_usd = -1")
    inject.set_defaults(func=cmd_inject)

    revert = sub.add_parser("revert-bad-row", help="delete the injected span")
    revert.set_defaults(func=cmd_revert)

    args = parser.parse_args(argv)
    client = TrinoClient(url=args.url) if args.url else TrinoClient()
    return int(args.func(client, args))


if __name__ == "__main__":
    sys.exit(main())
